version: '3.5'

services:
  postgres:
    container_name: my-postgres
    image: postgres:16
    ports:
      - "${POSTGRE_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRE_DB_NAME}
      POSTGRES_USER: ${POSTGRE_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRE_DB_PASSWORD}
    volumes:
      - ${POSTGRE_DB_VOLUME}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRE_DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=${ETCD_AUTO_COMPACTION_MODE}
      - ETCD_AUTO_COMPACTION_RETENTION=${ETCD_AUTO_COMPACTION_RETENTION}
      - ETCD_QUOTA_BACKEND_BYTES=${ETCD_QUOTA_BACKEND_BYTES}
      - ETCD_SNAPSHOT_COUNT=${ETCD_SNAPSHOT_COUNT}
    volumes:
      - ${ETCD_VOLUME}:/etcd
    command: etcd -advertise-client-urls=${ETCD_ADVERTISE_URL} -listen-client-urls ${ETCD_LISTEN_URL} --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_CONSOLE_PORT}:9001"
      - "${MINIO_PORT}:9000"
    volumes:
      - ${MINIO_VOLUME}:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.17
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS}
      MINIO_ADDRESS: ${MINIO_ADDRESS}
    volumes:
      - ${MILVUS_VOLUME}:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "${MILVUS_PORT}:19530"
      - "${MILVUS_API_PORT}:9091"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus