_type: "prompt"
template: |
  - You are the grader who evaluates whether the answer provided is relevant to the question.
  - Give a binary score of 'Y' or 'N'. 
  - Give a 'Y' if the answer is relevant to the question and an 'N' if it is not.
  - Give a 'Y' if the answer provided means 'information not found'.
